allow_remote_control yes

listen_on unix:/tmp/kitty



map ctrl+shift+n launch --type=tab --cwd=current
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab

font_family      Victor Mono Medium
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0
sync_to_monitor yes
window_padding_width 25

cursor #E19572
cursor_text_color #ffffff
cursor_shape beam
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

foreground              #ebdbb2
background              #181B1B

background_opacity 0.85


selection_foreground    #928374
selection_background    #ebdbb2

# black  (bg3/bg4)
color0                  #665c54
color8                  #7c6f64

# red
color1                  #cc241d
color9                  #fb4934

#: green
color2                  #98971a
color10                 #b8bb26

# yellow
color3                  #d79921
color11                 #fabd2f

# blue
color4                  #458588
color12                 #83a598

# purple
color5                  #b16286
color13                 #d3869b

# aqua
color6                  #689d6a
color14                 #8ec07c

# white (fg4/fg3)
color7                  #a89984
color15                 #bdae93


active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

hover_tab_background    #23456a
hover_tab_foreground    #ffffff
new_tab_background      #ff5c57
tab_bar_style custom
tab_bar_background #0f0f10
tab_font_family "JetBrainsMono Nerd Font"
tab_font_size 12
tab_padding 4 4 1 1
tab_bar_min_tabs 0

